In [1]:
import numpy as np

In [32]:
print("a: ")
a = np.asarray([1,2,3]) #[1 2 3]
print(np.shape(a)) #(3,)

print("b: ")
b = a.reshape(1,3) #[[1 2 3]]
print(np.shape(b)) #(1,3)

print("c: ")
c = (np.asarray(b[0][0:2])).reshape(1,2)

print(np.shape(c))
print(c)

a: 
(3,)
b: 
(1, 3)
c: 
(1, 2)
[[1 2]]


In [34]:
d = np.eye(3)
e = np.dot(d,a)
print(e)

[1. 2. 3.]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])